auth/urls.py
from django.urls import path

from auth import views

urlpatterns = [
  path('login/', views.Login.as_view()),
  path('logout/', views.Logout.as_view())
]

hackerpy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from main import views

urlpatterns = [
  path('', views.Index.as_view()),
  path('contests', views.Contests.as_view(), name = 'contests'),
  path('contests/<int:pk>', login_required(views.Contest.as_view()), name = 'contest'),
  path('contests/<int:contest_id>/problem/<int:pk>', login_required(views.Problem.as_view()), name = 'problem'),
  path('problem_create/', views.ProblemCreate.as_view())
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import markdown2

# Create your models here.
class Problem(models.Model):
  LEVEL_CHOICES = [
    (1, 'Easy'),
    (2, 'Medium'),
    (3, 'Difficult')
  ]

  name = models.CharField(max_length = 256)
  description = models.TextField()
  level = models.IntegerField(choices = LEVEL_CHOICES)

# Computed property
  @property
  def description_html(self):
    return markdown2.markdown(self.description)

  def __str__(self):
    return self.name

class Contest(models.Model):
  name = models.CharField(max_length = 256)
  description = models.TextField()
  start_date = models.DateTimeField()
  end_date = models.DateTimeField()
  is_private = models.BooleanField(default = False)
  problems = models.ManyToManyField('Problem')

  def __str__(self):
    return self.name

class StudentContest(models.Model):
  contest = models.ForeignKey('Contest', on_delete = models.CASCADE)
  user = models.ForeignKey(User, on_delete = models.CASCADE)

  def __str__(self):
    return "{} - {}".format(self.user, self.contest)

class Submission(models.Model):
  LANGUAGES = [
    (1, 'cpp'),
    (2, 'c'),
    (3, 'java'),
    (4, 'python')
  ]

  user = models.ForeignKey(User, on_delete = models.CASCADE)
  contest = models.ForeignKey('Contest', on_delete = models.CASCADE)
  problem = models.ForeignKey('Problem', on_delete = models.CASCADE)
  source = models.TextField()
  language = models.IntegerField(choices = LANGUAGES)
  score = models.IntegerField(null = True)
  createdAt = models.DateTimeField(auto_now_add = True)

main/forms.py
from django import forms

class LoginForm(forms.Form):
  username = forms.CharField()
  password = forms.CharField(widget = forms.PasswordInput)

main/views.py
from django.shortcuts import render
from django.views.generic import (
  TemplateView,
  ListView,
  DetailView,
  CreateView
)

from main import models

# Create your views here.
class Index(TemplateView):
  template_name = 'main/index.html'

class Contests(ListView):
  model = models.Contest
  template_name = 'main/contests.html'

class Contest(DetailView):
  model = models.Contest
  template_name = 'main/contest.html'

class ProblemCreate(CreateView):
  model = models.Problem
  template_name = 'main/problem_create.html'
  fields = '__all__'
  success_url = '/'

class Problem(DetailView):
  template_name = 'main/problem.html'

  def get_queryset(self):
    return models.Contest.objects.get(id = self.kwargs['contest_id']).problems

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Hacker.py</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contests' %}">Contests</a>
          </li>
          <li class="nav-item">
            {% if request.user.is_authenticated %}
              Hello, {{request.user.first_name}}
              <a class="btn btn-danger" href="/auth/logout">Logout</a>
            {% else %}
              <a class="btn btn-success" href="/auth/login">Login</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

templates/main/components/contest_card.html
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ contest.name }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ contest.start_date }}</h6>
    <p class="card-text">
      {{contest.description}}
    </p>
    <a href="{% url 'contest' contest.id %}" class="card-link">Attempt</a>
  </div>
</div>

templates/main/components/problem_card.html
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ problem.name }}</h5>
    <p class="card-text">
      {% autoescape off %}
        {{ problem.description_html }}
      {% endautoescape %}
    </p>
    <a href="{% url 'problem' contest_id=contest.id pk=problem.id %}" class="card-link">Attempt</a>
  </div>
</div>

templates/main/contest.html
{% extends 'base.html' %}

{% block content %}

  <div class="row">
    <h1>{{ contest.name }}</h1>
  </div>
  <p>{{ contest.start_date }} - {{ contest.end_date }}</p>
  <p>{{ contest.description }}</p>
  <div class="row">
    {% for problem in contest.problems.all %}
      <div class="col-4">
        {% include 'main/components/problem_card.html' %}
      </div>
    {% endfor %}
  </div>

{% endblock %}

templates/main/contests.html
{% extends 'base.html' %}

{% block content %}

  <div class="row">
    {% for contest in contest_list %}
      <div class="col-4">
        {% include 'main/components/contest_card.html' %}
      </div>
    {% endfor %}
  </div>

{% endblock %}

templates/main/index.html
{% extends 'base.html' %}

{% block content %}

  <div class="justify-content-center">
    <h1>Welcome to Hacker.py</h1>
  </div>

{% endblock %}

templates/main/problem.html
{% extends 'base.html' %}

{% block content %}

  <div class="row">
    <h1>{{ problem.name }}</h1>
  </div>

  <div class="row">
    <p>
      {% autoescape off %}
        {{ problem.description_html }}
      {% endautoescape %}
    </p>
  </div>

  <div id="editor" style="height: 300px"></div>
      
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.5/ace.js" type="text/javascript" charset="utf-8"></script>
  <script>
      var editor = ace.edit("editor");
      editor.setTheme("ace/theme/monokai");
      editor.session.setMode("ace/mode/python");
  </script>

{% endblock %}

templates/main/problem_create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
  </form>
</body>
</html>